### ISSUE TITLE
Remove additional Edge components.

### ISSUE THREAD

**Issue by T0m0rr0w** [ShadowWhisperer/Remove-Edge-Chromium#4]
Hi. Would it be possible to add Edge Update and WebView2 Runtime to the script?
Also while the script worked there is still a 48KB entry of Edge itself under Installed Programs for some reason.
Would be great if the script got rid of all 3 entries.

**Comment by ShadowWhisperer** [comment]
Hey,

The script has been updated to remove _WebView_.
The update folder also goes away, when that is removed.

Run the script again, and check if the 48KB still remains.  I'm not certain to where you are referring.

**Comment by T0m0rr0w** [comment]
Thank you for the quick update. Edge, Edge Update and WebView2 were all properly removed with the updated script. Only some empty folders are left where they used to be.

For some reason Settings > Apps > Installed Apps still shows Microsoft Edge with 48KB size and whatever build number of the OS is based on. So im guessing this might be some kind of included installer package. Possibly in WinSxS folder tho none of those are 48KB in there (some are smaller, same bigger). Oddly 3rd party programs such as CCleaner do not show this 48KB leftover in installed programs list.

I mean it's not a big deal. Mostly visual annoyance that it's still there.
I tested the script on two Windows 11 builds in VM: 22621 (beta) and 25145 (dev).
I currently not not have any Windows 10 ISO's to test (downloading now) so maybe this lefover appears only in Windows 11?
