### ISSUE TITLE
Didn't work

### ISSUE THREAD

**Issue by SightUp** [ShadowWhisperer/Remove-Edge-Chromium#6]
I ran your .bat file. It removed the icon from the desktop, but that's about it.
Here is the output.
![image](https://user-images.githubusercontent.com/52366473/177917172-66a78e5d-6d1a-4a15-8ff2-125b2acda311.png)

Here is a few locations I still see it.
![image](https://user-images.githubusercontent.com/52366473/177917219-c386706c-668f-4efc-8482-536c3e10849c.png)
![image](https://user-images.githubusercontent.com/52366473/177917279-9b28589c-5248-47e9-baa0-27b42b14f7d0.png)
![image](https://user-images.githubusercontent.com/52366473/177917373-a1716f0a-0239-4a8a-8714-328672e7a5b1.png)

**Comment by ShadowWhisperer** [comment]
I ran it on my main system and it runs fine.  I tried it again in a virtual machine and I get the same results as you.
Looks like I moved some code earlier today. Reinstall Edge and run it again.  **https://www.microsoft.com/en-us/edge**

Sorry for any inconveniences.  Let me know if you have more issues.

The 48KB is a folder that comes back after a reboot. [HERE](https://github.com/ShadowWhisperer/Remove-Edge-Chromium/issues/4)  
I haven't figured out a way to remove it from that programs list.  Start menu shortcut should go away now.

**Comment by SightUp** [comment]
I did what you asked actually. I uninstalled it originally with a more basic removal function.

**Comment by ShadowWhisperer** [comment]
So it removed now?

*I should have mention in the previous post, I updated the script.

**Comment by SightUp** [comment]
Same issue. But I had to remove the run as admin part. I right clicked and ran as admin but the script didn't detect that I was.

**Comment by ShadowWhisperer** [comment]
Strange.  I have a bunch of new computers that are coming in tomorrow, at work. I'll do some more testing on them, and see what happens.

**Comment by ShadowWhisperer** [comment]
I do not have Discord. I believe you, that it wont run on your system.  

I've run it on several more machines that customers have brought into my shop, and haven't had any issues.  

Judging by `I right clicked and ran as admin but the script didn't detect that I was`, there's probably something wrong with your install of Windows. I've been using the detect admin section for a number of years, and haven't seen that issue before.

**Comment by SightUp** [comment]
I think it has something to do with .bat file functions. I have removed a ton of stuff from Windows and turned off services. Are you familiar with any services that would hinder this? 

I had another script I got out of Github to remove OneDrive. I had to remove the admin verification line for it to work.

Yours works if I remove that line, too. I just get what you see above.

**Comment by ShadowWhisperer** [comment]
These are the services I have running. I don't know which/if it's a serve that controls that.
![services](https://user-images.githubusercontent.com/61057625/178068010-0056c005-258d-4234-8b9b-a42e41867174.PNG)
