### ISSUE TITLE
Problem: Still Edge in Task manager after unistall completely edge.

### ISSUE THREAD

**Issue by zbabyz** [ShadowWhisperer/Remove-Edge-Chromium#8]
Please can you fix for force uninstall the Microsoft Edge in [ task manager > App History (tab) ] I want to permanent uninstall after windows update so no problem.

I did force uninstalled edge everything when its gone in task manager (App history) then I updated in Windows 10 when it's back Edge in Task manager. 

Note: Sorry For My Bad English

thank you. let me know

<a href="https://ibb.co/FhHPF57"><img src="https://i.ibb.co/FhHPF57/asd.png" alt="asd" border="0"></a>

**Comment by zbabyz** [comment]
There was nothing in the folder. 

here is picture.
<a href="https://ibb.co/DYWY1f7"><img src="https://i.ibb.co/DYWY1f7/zx.png" alt="zx" border="0"></a>

**Comment by ShadowWhisperer** [comment]
If that folder is blank, the Chrome based version of Edge is removed.
The built in version of Edge, is not removed by this script.  

Try these steps, to disable it.
`https://silicophilic.com/disable-microsoft-edge/`
